Solution
mate-academy/py-taxi-service-authentication pull request #100
Opened 2022-11-03 14:55 UTC by kateryna3k

<img width="1394" alt="Screenshot 2022-11-03 at 16 05 48" src="https://user-images.githubusercontent.com/111740601/199754921-3662069c-4bab-46ff-a733-6c9e2057d5f1.png">
<img width="1394" alt="Screenshot 2022-11-03 at 16 05 57" src="https://user-images.githubusercontent.com/111740601/199754951-7cfce730-da9f-4898-bb1e-37cadb968302.png">
<img width="1394" alt="Screenshot 2022-11-03 at 16 06 01" src="https://user-images.githubusercontent.com/111740601/199754975-c31e3786-25e5-4478-b332-59a986081f4e.png">
<img width="1394" alt="Screenshot 2022-11-03 at 16 06 25" src="https://user-images.githubusercontent.com/111740601/199754994-b35cb331-0194-4d00-b5c8-96ae0e61f458.png">
<img width="1394" alt="Screenshot 2022-11-03 at 16 06 32" src="https://user-images.githubusercontent.com/111740601/199755013-677aaaf5-d4e7-4bb5-9323-3200dec9c771.png">
<img width="1394" alt="Screenshot 2022-11-03 at 16 06 47" src="https://user-images.githubusercontent.com/111740601/199755030-6f82932e-995e-4be8-8966-305ad9ef03fc.png">

2022-11-05 22:43 UTC, FranchukS requested changes

2022-11-05 22:43 UTC, FranchukS commented on templates/includes/sidebar.html
> +    <li>User: {{ user.username }}</li>
There must be a link to the user's detail page on the username (readme task #3)

2022-11-06 11:56 UTC, FranchukS approved these changes
Well done!

2022-11-07 09:07 UTC, MasterpieceElbow approved these changes
GJ!

2024-10-02 07:36 UTC, closed without merging