Solution
mate-academy/py-taxi-service-authentication pull request #105
Opened 2022-11-03 20:38 UTC by HStakhiv

![image](https://user-images.githubusercontent.com/25363499/199828781-7e52b1ed-ac26-4d8e-a9ba-b0b4805fb7b3.png)
![image](https://user-images.githubusercontent.com/25363499/199828899-d2e86d1e-211c-4ac5-aaf0-822fa557fba5.png)
![image](https://user-images.githubusercontent.com/25363499/199829000-cd9ba4a6-8278-4040-98ea-87b6836fe6fc.png)
![image](https://user-images.githubusercontent.com/25363499/199829062-3feae12e-49f9-424b-900b-9bdef435875e.png)
![image](https://user-images.githubusercontent.com/25363499/199829144-21f6fd4a-9d42-4c3f-b10b-7c2eb7e375ab.png)

2022-11-04 10:47 UTC, skrypka-dmytro approved these changes
Looks good

2022-11-07 16:24 UTC, Nattalli requested changes

2022-11-07 16:24 UTC, Nattalli commented on taxi/views.py
>      queryset = Driver.objects.all().prefetch_related("cars__manufacturer")
and here

2022-11-07 16:32 UTC, Nattalli approved these changes
Well done!

2024-12-13 08:19 UTC, closed without merging